name: simple build test

on:
  # Runs on all pushes
  push:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: vite build
        run: npm run build 
      - name: copy to 404
        run: cp dist/index.html dist/404.html

